name 'rsyslog-server'
maintainer 'Jeevan Dongre'
maintainer_email 'jeevan.dongre@gmail.com'
license 'all_rights'
description 'Installs/Configures rsyslog-server'
long_description 'Installs/Configures rsyslog-server'
version '0.1.0'
